# Generated by Django 6.0.2 on 2026-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
