# Generated by Django 6.0.2 on 2026-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='answer',
            field=models.JSONField(),
        ),
    ]
