# Generated by Django 6.0.2 on 2026-02-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0005_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
