# Generated by Django 6.0.2 on 2026-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0006_chatmessage_rated_at_chatmessage_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='rl_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rl_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
